config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :links, only: [:index, :update]
    end
  end

  root 'static_pages#index'

  get '/sessions/new', to: 'sessions#new', as: :login
  post '/sessions/create', to: 'sessions#create', as: :sessions_create
  get '/users/new', to: 'users#new', as: :sign_up
  post '/users/create', to: 'users#create', as: :users_create
  delete '/sessions/destroy', to: 'sessions#destroy', as: :sessions_destroy
  get 'links/index', to: 'links#index', as: :links_index
  post 'link/create', to: 'links#create'
  get 'links/edit/:id', to: 'links#edit', as: :links_edit
  put 'links/update/:id', to: 'links#update', as: :links_update
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  validates_presence_of :title
  validates :url_string, :url => true
  before_save :nil_false

  def nil_false
    if read == nil
      self.read = false
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_presence_of :email
  validates :password, confirmation: true
  validates :email, uniqueness: true
  has_many :links

end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController

  def index
    @links = Link.where(user_id: current_user.id)
    render json: @links
  end

  def update
    link = Link.find_by(id: params[:id])
    link.update_attributes(update_params)
    render json: link
  end

  private
  def update_params
    params.require(:link).permit(:title, :url_string, :read)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @link = Link.new
    @links = current_user.links
  end

  def create
    link = current_user.links.new(link_params)
    if link.save
      flash[:success] = "Link Created"
    else
      flash[:danger] = link.errors.full_messages.join(", ")
    end
    redirect_to links_index_path
  end

  def edit
    @link = current_user.links.find_by(id: params[:id])
  end

  def update
    link = current_user.links.find_by(id: params[:id])
    link.update_attributes(link_params)
    redirect_to links_index_path
  end

  private
  def link_params
    params.require(:link).permit(:url_string, :title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(email: user_params[:email])
    if @user && @user.authenticate(user_params[:password])
      flash[:success] = "Welcome #{user_params[:email]}"
      session[:user_id] = @user.id
      redirect_to links_index_path
    else
      flash[:danger] = "Invalid Login"
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      flash[:success] = "Welcome #{user_params[:email]}"
      session[:user_id] = user.id
      redirect_to links_index_path
    else
      flash[:danger] = user.errors.full_messages.join(", ")
      redirect_to sign_up_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/api/v1/links_helper.rb
module Api::V1::LinksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="nav navbar navbar-default">
  <div class='container-fluid'>
    <div class='navbar-header'>
      <% if current_user %>
        <p class='navbar-text'><%= link_to "Links Index", links_index_path %></p>
        <p class='navbar-text'>Hello <%= current_user.email %></p>
        <p class='navbar-text'><%= link_to "Sign Out", sessions_destroy_path, method: "delete" %></p>
      <% else %>
        <p class='navbar-text'><%= link_to "Log In", login_path %></p>
        <p class='navbar-text'><%= link_to "Sign Up", sign_up_path %></p>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thoughtbox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <%= render partial: "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/links/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Edit  <span class="link unread"><%= @link.title %></span></h1>
  </div>
  <div class="row edit-form">
    <%= form_for @link, url: links_update_path, method: "PUT" do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control", value: @link.title %><br />
      <%= f.label :url_string %>
      <%= f.text_field :url_string, class: "form-control", value: @link.url_string %><br />
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/links/index.html.erb
<div class="container">
  <h1>Links Index</h1>
  <div class="row">
    <div class='col-md-4'>
      <%= form_for @link, url: link_create_path do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %><br  />
        <%= f.label :url_string %>
        <%= f.text_field :url_string, class: "form-control" %><br />
        <%= f.submit "Create Link" %>
      <% end %>
    </div>
  </div><br />
  <div class="row well" id="searchDiv">
    <h3>Filters</h3>
    <div class="col-md-2">
      <input id="searchField" class="form-control" type="text" name="searchTerm" value="Enter Search Term">
    </div>
    <div class="col-md-1">
      <button type="button" name="search" class="btn btn-default search">Search</button>
    </div>
    <div class="col-md-1">
      <button type="button" name="read-filter" class="btn btn-default read-filter">Read</button>
    </div>
    <div class="col-md-1">
      <button type="button" name="unread-filter" class="btn btn-default unread-filter">Unread</button>
    </div>
    <div class="col-md-1">
      <button type="button" name="alphabetical-sort" class="btn btn-default alphabetical-sort">Alpha</button>
    </div>
    <div class="col-md-1">
      <button type="button" name="clear-search" class="btn btn-default clear-search">Clear Filter</button>
    </div>
  </div><br />
  <div class="row">
    <div class="well" id="linksDiv">
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |name, message| %>
<div class=<%= "alert-#{name}" %> >
  <%= content_tag :div, message.html_safe, id: "flash_#{name}", class: "container"%>
</div>
<% end %>

app/views/static_pages/index.html.erb
<div class="container">
  <div class="row">
    <h1>Welcome to ThoughtBox!</h1>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <h1>New User Account</h1>
  </div>
  <div class="row new-user-form col-md-4">
    <%= form_for @user, url: users_create_path, method: "POST" do |f| %>
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
      <%= f.label :password %>
      <%= f.text_field :password, class: "form-control" %>
      <%= f.label :password_confirmation %>
      <%= f.text_field :password_confirmation, class: "form-control" %><br />
      <%= f.submit %>
    <% end %>
  </div>
</div>